kind: pipeline
name: default

trigger:
  event:
    - push
    - pull-request

steps:
  - name: test
    image: tujoworker/docker-node-puppeteer
    commands:
      - yarn install
      - yarn lint-ci
      - yarn test-ci
    when:
      event:
        - push
      branch:
        exclude:
          - release
          - develop
          - gh-pages
          - rc/*

  - name: deploy-preview
    image: tujoworker/docker-node-puppeteer
    environment:
      FIGMA_MAIN_FILE:
        from_secret: FIGMA_MAIN_FILE
      FIGMA_TOKEN:
        from_secret: FIGMA_TOKEN
      GH_EMAIL:
        from_secret: GH_EMAIL
      GH_NAME:
        from_secret: GH_NAME
      GH_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - yarn install
      - yarn audit-ci
      - yarn lint-ci
      - yarn test-ci
      - yarn prepublish-ci
      - yarn build-ci
      - yarn test-ci-screenshots
    when:
      event:
        - push
      branch:
        include:
          - develop
          - rc/*

  - name: deploy-pull-preview
    image: tujoworker/docker-node-puppeteer
    environment:
      FIGMA_MAIN_FILE:
        from_secret: FIGMA_MAIN_FILE
      FIGMA_TOKEN:
        from_secret: FIGMA_TOKEN
      GH_EMAIL:
        from_secret: GH_EMAIL
      GH_NAME:
        from_secret: GH_NAME
      GH_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - yarn install
      - yarn audit-ci
      - yarn lint-ci
      - yarn test-ci
      - yarn prepublish-ci
      - yarn build-ci
      - yarn test-ci-screenshots
    when:
      event:
        - pull-request

  - name: deploy-release
    image: tujoworker/docker-node-puppeteer
    environment:
      FIGMA_MAIN_FILE:
        from_secret: FIGMA_MAIN_FILE
      FIGMA_TOKEN:
        from_secret: FIGMA_TOKEN
      GH_EMAIL:
        from_secret: GH_EMAIL
      GH_NAME:
        from_secret: GH_NAME
      GH_TOKEN:
        from_secret: GH_TOKEN
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - yarn install
      - yarn audit-ci
      - yarn lint-ci
      - yarn test-ci
      - yarn prepublish-ci
      - yarn build-ci
      - yarn test-ci-screenshots
      - yarn deploy-ci
      - yarn publish-ci
    when:
      event:
        - push
      branch:
        include:
          - release

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: dnb-design-system
      username: DroneCI
      icon_url: https://github.com/drone/brand/blob/master/logos/png/drone-logo_256.png?raw=true
    when:
      status: [success, failure]
