# Javascript Node Travis configuration file
#
language: node_js

node_js:
  - '10.6'

# os:
#   - osx

notifications:
  email: false
  slack: eggsdesign:MOctggZdt8nWoWScG08NZ5ap

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

jobs:
  include:
    - stage: test
      name: Run static and jest tests
      script: yarn lint-ci && yarn test-ci

    - stage: deploy-preview
      name: Build a portal preview
      script: yarn prepublish-ci && yarn build-ci

    - stage: deploy-release
      name: Deploy portal and make eventually NPM release
      script: yarn prepublish-ci && yarn build-ci && yarn deploy-ci && yarn publish-ci

stages:
  - name: test
    if: NOT (branch =~ /^(release|gh-pages)/)

  - name: deploy-preview
    if: (branch =~ /^(develop|rc\/.*)/)

  - name: deploy-release
    if: (branch = release)
