# Javascript Node Travis configuration file
#
language: node_js

node_js:
  - '10.6'

cache:
  yarn: true

notifications:
  email: false

jobs:
  include:
    - stage: test
      name: Run static and jest tests
      script: yarn lint-ci && yarn test-ci

    - stage: deploy-preview
      name: Build the portal
      script: yarn prepublish-ci && yarn build-ci

    - stage: release
      name: Release on NPM
      script: yarn prepublish-ci && yarn build-ci && yarn deploy-ci && yarn publish-ci

stages:
  - name: test
    if: branch != /^master|^develop|^gh-pages|^rc-.*|^rc\/.*|^release-.*|^release\/.*/

  - name: deploy-preview
    if: branch = /^develop|^rc-.*|^rc\/.*/

  - name: release
    if: branch = /^master|^release-.*|^release\/.*/
