# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn lint-ci
      - run: yarn test-ci

  deploy-preview:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Prepublish the ui-lib and commit changes
          command: yarn prepublish-ci

      - run:
          name: Build the portal, just to test if the build is successful
          command: yarn build-ci

  deploy-release:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Prepublish the ui-lib to use it in "build-ci"
          command: yarn prepublish-ci

      - run:
          name: Build the portal
          command: yarn build-ci

      - run:
          name: Deploy the portal
          command: yarn deploy-ci

      - run:
          name: Release on NPM
          command: yarn publish-ci

workflows:
  version: 2
  workflow:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - gh-pages
                - /^(release\/|rc-|rc\/).*/
      - deploy-preview:
          filters:
            branches:
              only:
                - develop
                - /^(rc-|rc\/).*/
      - deploy-release:
          filters:
            branches:
              only:
                - master
                - /^release\/.*/
