# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout
      - save_cache:
          name: Save Repo Cache
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  install_dependencies:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - restore_cache:
          name: Restore Repo Cache
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  publish:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - restore_cache:
          name: Restore Repo Cache
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: prepublish
          command: yarn prepublish-ci

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: release
          command: yarn publish-ci

  deploy:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - restore_cache:
          name: Restore Repo Cache
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: prepublish
          command: yarn prepublish-ci

      - run:
          name: build
          command: yarn build-ci

      - run:
          name: deploy
          command: yarn deploy-ci

  test:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - restore_cache:
          name: Restore Repo Cache
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn lint-ci
      - run: yarn test-ci
      - run: yarn prepublish-ci
      - run: yarn build-ci

workflows:
  version: 2
  workflow:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
          filters:
            branches:
              ignore:
                - master
                - gh-pages
      - publish:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - master
                - /rc-.*/
      - deploy:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - master
                - /rc-.*/
