# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Prepublish the ui-lib
          command: yarn prepublish-ci

      - run:
          name: Build the portal
          command: yarn build-ci

      - run:
          name: Deploy the portal
          command: yarn deploy-ci

      - run:
          name: Release on NPM
          command: yarn publish-ci

  test:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn lint-ci
      - run: yarn test-ci
      - run: yarn prepublish-ci
      - run: yarn build-ci

workflows:
  version: 2
  workflow:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - /.*rc-.*|^rc\//
                - /.*wip-.*|^wip\//
                - gh-pages
      - deploy:
          filters:
            branches:
              only:
                - master
                - /.*rc-.*|^rc\//
